try:
    foo()
except ArithmeticError:
    print('ArithmeticError')
except AssertionError:
    print('AssertionError')

